### ISSUE TITLE
Image of what to click in CORS options does not show

### ISSUE THREAD

**Issue by ghost** [Dredanarchy/Advanced-Dredark-Tools-v2#3]
Could you maybe reply the option I need to click?

**Comment by Cheesegle** [comment]
You just need to enable CORS requests like it shows in the video on the extension page.
Also like it is stated in README, I recommend that you DON'T use this as the anticheat will detect you and get you banned.

**Comment by ghost** [comment]
> You just need to enable CORS requests like it shows in the video on the extension page. Also like it is stated in README, I recommend that you DON'T use this as the anticheat will detect you and get you banned.

I think the anticheat wont work on test mode

**Comment by ghost** [comment]
>btw I love your idea.
